#include "core/effects/trail_effect.h"
#include <utility>
#include <cmath>
namespace vt {
TrailEffect::TrailEffect(QString id, QString name):m_id(std::move(id)),m_name(std::move(name)){}
QString TrailEffect::typeId()const{return m_id;} QString TrailEffect::displayName()const{return m_name;}
EffectDomain TrailEffect::domain()const{return EffectDomain::Generator;} std::unique_ptr<Effect> TrailEffect::clone()const{return std::make_unique<TrailEffect>(*this);}
QVector<EffectParameter> TrailEffect::parameterDefinitions()const{return {{"copyCount","Copy count",double(m_count),1,12,1,true},{"offsetX","Offset X",m_offsetX,-1,1,.01,false},{"offsetY","Offset Y",m_offsetY,-1,1,.01,false},{"rotationStep","Rotation",m_rotation,-45,45,1,false},{"scaleStep","Scale",m_scale,.1,1.5,.01,false},{"opacityDecay","Opacity decay",m_decay,.1,1,.01,false}};}
bool TrailEffect::setParameter(const QString&i,double v){if(i=="copyCount")m_count=qBound(1,qRound(v),12);else if(i=="offsetX")m_offsetX=qBound<qreal>(-1,v,1);else if(i=="offsetY")m_offsetY=qBound<qreal>(-1,v,1);else if(i=="rotationStep")m_rotation=qBound<qreal>(-45,v,45);else if(i=="scaleStep")m_scale=qBound<qreal>(.1,v,1.5);else if(i=="opacityDecay")m_decay=qBound<qreal>(.1,v,1);else return false;return true;}
QJsonObject TrailEffect::parametersToJson()const{return {{"copyCount",m_count},{"offsetX",m_offsetX},{"offsetY",m_offsetY},{"rotationStep",m_rotation},{"scaleStep",m_scale},{"opacityDecay",m_decay}};}
bool TrailEffect::parametersFromJson(const QJsonObject&o,QString*e){for(const auto&p:parameterDefinitions())if(!setParameter(p.id,o.value(p.id).toDouble(p.value))){if(e)*e="Invalid trail parameter.";return false;}return true;}
void TrailEffect::apply(VectorGeometry& g,const EffectContext& c)const{const qreal s=c.effectiveStrength(*this);if(qFuzzyIsNull(s))return;const QVector<GeometryPiece> originals=g.pieces;constexpr int cap=4096;for(const GeometryPiece& base:originals){if(!scope.includes(base.sourceClusterStart,base.sourceClusterLength)||base.generationDepth>=2)continue;for(int n=1;n<=m_count&&g.pieces.size()<cap;++n){GeometryPiece copy=base;copy.generationDepth=base.generationDepth+1;copy.generatorEffectId=instanceId;copy.opacityMultiplier=qBound<qreal>(0,base.opacityMultiplier*std::pow(m_decay,n)*s,1);const QPointF center=copy.path.boundingRect().center();QTransform t;t.translate(center.x()+n*m_offsetX*c.referenceHeight*s,center.y()+n*m_offsetY*c.referenceHeight*s);t.rotate(n*m_rotation*s);t.scale(std::pow(m_scale,n*s),std::pow(m_scale,n*s));t.translate(-center.x(),-center.y());copy.path=t.map(copy.path);copy.anchor=t.map(copy.anchor);g.pieces.push_back(std::move(copy));}}g.recomputeBounds();}
}
